name: Build C Project

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make

      - name: Install arm_sdk
        run: make arm_sdk_install

      - name: Build the project
        run: make fsesc_75_200_alu

      - name: Check build output
        run: |
          BIN_PATH=$(find . -path './build/fsesc_75_200_alu/*.bin' | head -1)
          if [ -z "$BIN_PATH" ]; then
            echo "##[error] 文件路径不匹配"
            exit 1
          fi
          if [ ! -f "$BIN_PATH" ]; then
            echo "##[error] 文件不存在"
            exit 1
          fi
          echo "Build succeeded! File path: $BIN_PATH"
          echo "bin_path=$BIN_PATH" >> $GITHUB_OUTPUT  # 将路径写入 GitHub 输出

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fsesc_75_200_alu_binaries
          path: ./build/fsesc_75_200_alu/*.bin  # 直接指定路径
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
